CREATE TABLE "registro_turni_ordinari" (
	"id" UUID NOT NULL UNIQUE,
	"data" DATE NOT NULL,
	"turno_id" INTEGER NOT NULL,
	"agente_id" UUID,
	"impianto_id" UUID,
	"created_at" TIMESTAMPTZ,
	"updated_at" TIMESTAMPTZ,
	PRIMARY KEY("id")
);

CREATE TABLE "turni" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"codice" VARCHAR(255) NOT NULL,
	"nome" VARCHAR(255) NOT NULL,
	"orario_inizio" TIME,
	"orario_fine" TIME,
	"durata_minuti" INTEGER,
	"is_compensativo" BOOLEAN,
	"is_disponibilità" BOOLEAN,
	"is_riposo" BOOLEAN,
	"created_at" TIMESTAMPTZ,
	"updated_at" TIMESTAMPTZ,
	PRIMARY KEY("id")
);

CREATE TABLE "agenti" (
	"id" UUID NOT NULL UNIQUE,
	"nome" VARCHAR(255) NOT NULL,
	"cognome" VARCHAR(255) NOT NULL,
	"mansione_id" INTEGER,
	"matricola" INTEGER NOT NULL,
	"telefono1" INTEGER,
	"telefono2" INTEGER,
	"telefono3" INTEGER,
	"created_at" TIMESTAMPTZ,
	"updated_at" TIMESTAMPTZ,
	PRIMARY KEY("id")
);

CREATE TABLE "impianti" (
	"id" UUID NOT NULL UNIQUE,
	"nome" VARCHAR(255),
	"mansione_id" INTEGER,
	"nr_turni" INTEGER,
	"is_active" BOOLEAN,
	"created_at" TIMESTAMPTZ,
	"updated_at" TIMESTAMPTZ,
	PRIMARY KEY("id")
);

CREATE TABLE "mansione" (
	"id" INTEGER NOT NULL UNIQUE,
	"nome" VARCHAR(255),
	"is_active" BOOLEAN,
	"created_at" TIMESTAMPTZ,
	"updated_at" TIMESTAMPTZ,
	PRIMARY KEY("id")
);

CREATE TABLE "righello" (
	"id" UUID NOT NULL UNIQUE,
	"impianto_id" UUID,
	"nome" VARCHAR(255),
	"posizioni" INTEGER,
	"data_inizio" DATE,
	"is_active" BOOLEAN,
	"created_at" TIMESTAMPTZ,
	"updated_at" TIMESTAMPTZ,
	PRIMARY KEY("id")
);

CREATE TABLE "posizione" (
	"id" UUID NOT NULL UNIQUE,
	"agente_id" UUID,
	"righello_id" UUID NOT NULL,
	"numero" INTEGER NOT NULL,
	"sequenza" INTEGER,
	"created_at" TIMESTAMPTZ,
	"updated_at" TIMESTAMPTZ,
	PRIMARY KEY("id")
);

CREATE TABLE "turni_ciclo" (
	"id" UUID NOT NULL UNIQUE,
	"turno_id" INTEGER,
	"posizione_id" UUID,
	"turno_sequenza" INTEGER,
	"created_at" TIMESTAMPTZ,
	"updated_at" TIMESTAMPTZ,
	PRIMARY KEY("id")
);

CREATE TABLE "ciclicità" (
	"id" UUID NOT NULL UNIQUE,
	"nome" VARCHAR(255) NOT NULL,
	"descrizione" TEXT NOT NULL,
	"created_at" TIMESTAMPTZ,
	"updated_at" TIMESTAMPTZ,
	PRIMARY KEY("id")
);

CREATE TABLE "turni_ciclicità" (
	"id" UUID NOT NULL UNIQUE,
	"turno_id" INTEGER,
	"ciclicità_id" UUID,
	"turno_sequenza" INTEGER,
	"created_at" TIMESTAMPTZ,
	"updated_at" TIMESTAMPTZ,
	PRIMARY KEY("id")
);

CREATE TABLE "turni_estemporanei" (
	"id" UUID NOT NULL UNIQUE,
	"codice" VARCHAR(255) NOT NULL,
	"nome" VARCHAR(255) NOT NULL,
	"impianto_id" UUID,
	"orario_inizio" TIME,
	"orario_fine" TIME,
	"durata_minuti" INTEGER,
	"created_at" TIMESTAMPTZ,
	"updated_at" TIMESTAMPTZ,
	PRIMARY KEY("id")
);

CREATE TABLE "registro_estemporanei" (
	"id" UUID NOT NULL UNIQUE,
	"data" DATE NOT NULL,
	"estemporaneo_id" UUID NOT NULL,
	"agente_id" UUID,
	"created_at" TIMESTAMPTZ,
	"updated_at" TIMESTAMPTZ,
	PRIMARY KEY("id")
);

CREATE TABLE "assenze" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"codice" VARCHAR(255) NOT NULL,
	"nome" VARCHAR(255) NOT NULL,
	"is_compensativo" BOOLEAN,
	"is_riposo" BOOLEAN,
	"created_at" TIMESTAMPTZ,
	"updated_at" TIMESTAMPTZ,
	PRIMARY KEY("id")
);

CREATE TABLE "registro_assenze" (
	"id" UUID NOT NULL UNIQUE,
	"data" DATE NOT NULL,
	"assenza_id" INTEGER NOT NULL,
	"agente_id" UUID,
	"created_at" TIMESTAMPTZ,
	"updated_at" TIMESTAMPTZ,
	PRIMARY KEY("id")
);

ALTER TABLE "registro_turni_ordinari"
ADD FOREIGN KEY("turno_id") REFERENCES "turni"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "registro_turni_ordinari"
ADD FOREIGN KEY("agente_id") REFERENCES "agenti"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "registro_turni_ordinari"
ADD FOREIGN KEY("impianto_id") REFERENCES "impianti"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "impianti"
ADD FOREIGN KEY("id") REFERENCES "righello"("impianto_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "posizione"
ADD FOREIGN KEY("righello_id") REFERENCES "righello"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "posizione"
ADD FOREIGN KEY("agente_id") REFERENCES "agenti"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "turni_ciclo"
ADD FOREIGN KEY("posizione_id") REFERENCES "posizione"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "turni_ciclo"
ADD FOREIGN KEY("turno_id") REFERENCES "turni"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "agenti"
ADD FOREIGN KEY("mansione_id") REFERENCES "mansione"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "impianti"
ADD FOREIGN KEY("mansione_id") REFERENCES "mansione"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "turni_ciclicità"
ADD FOREIGN KEY("ciclicità_id") REFERENCES "ciclicità"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "turni_ciclicità"
ADD FOREIGN KEY("turno_id") REFERENCES "turni"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "turni_estemporanei"
ADD FOREIGN KEY("impianto_id") REFERENCES "impianti"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "turni_estemporanei"
ADD FOREIGN KEY("id") REFERENCES "registro_estemporanei"("estemporaneo_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "registro_estemporanei"
ADD FOREIGN KEY("agente_id") REFERENCES "agenti"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "assenze"
ADD FOREIGN KEY("id") REFERENCES "registro_assenze"("assenza_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "registro_assenze"
ADD FOREIGN KEY("agente_id") REFERENCES "agenti"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;